# Dockerfile for Celery worker
FROM python:3.9

WORKDIR /project

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /project/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /project/

