# docker-compose.yml
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      .env
    command: sh -c "chmod +x /project/migrate.sh && sh /project/migrate.sh && sh /project/entrypoint.sh"
    volumes:
      - .:/project
    depends_on:
      - db
      - redis
  db:
    image: postgres
    env_file:
      .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    env_file:
      .env
    command: celery -A bookstore_api worker --loglevel=info
    volumes:
      - .:/project
    depends_on:
      - db
      - web
      - redis
  
volumes:
    postgres_data:
