# docker-compose.yml
version: '3'

services:
  web:
    build: .
    command: python /project/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/project
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A bookstore_api worker --loglevel=info
    volumes:
      - .:/project
    depends_on:
      - db
      - web
      - redis
  
volumes:
    postgres_data:
