# docker-compose.yml
version: '3'

services:
  web:
    build: .
    command: python /project/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/project
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:
