name: CI/CD

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update
      run: sudo apt update
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r /bookstore_api/requirements.txt

    - name: Run tests
      run: |
        python manage.py test

    - name: Build Docker image
      run: |
        docker build -t online-book-store-backend .

    - name: Deploy to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: online-book-store-backend:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
